github/gh-actions-importer

- src/ActionsImporter.UnitTests/Services/DockerServiceTests.cs
- src/ActionsImporter/Services/DockerService.cs
This updates the `DockerService` to surround `--env` options in quotes so that values containing spaces are valid.
- Specs
```console
NO_PROXY="localhost, 127.0.0.1, ::1, .XXX.de, .YYY.de" dotnet run --project ActionsImporter/ActionsImporter.csproj -- dry-run ...
```
Closes #6
> Surround env variables with quotes

- src/ActionsImporter/Program.cs
This ensures that error messages get terminated with a newline character.
```bash
$ docker images rm ghcr.io/actions-importer/cli
$ dotnet run --project src/ActionsImporter/ActionsImporter.csproj -- audit jenkins -o output
```
Closes #16
> Terminate error messages with newline

- src/ActionsImporter.UnitTests/ActionsImporter.UnitTests.csproj
- src/ActionsImporter/Commands/AzureDevOps/Audit.cs
- src/ActionsImporter/Commands/AzureDevOps/BuildPipeline/DryRun.cs
- src/ActionsImporter/Commands/AzureDevOps/BuildPipeline/Migrate.cs
- src/ActionsImporter/Commands/AzureDevOps/Common.cs
- src/ActionsImporter/Commands/AzureDevOps/DryRun.cs
- src/ActionsImporter/Commands/AzureDevOps/Migrate.cs
- src/ActionsImporter/Commands/AzureDevOps/ReleasePipeline/DryRun.cs
- src/ActionsImporter/Commands/AzureDevOps/ReleasePipeline/Migrate.cs
Make sure you have the latest version of the Valet container: 
`gh actions-importer update`
Build c# project:
`dotnet build src/ActionsImporter/ActionsImporter.csproj `
Make sure you add a sample ADO pipeline to `output/pipeline.yml`
```
trigger:
- main
pool:
vmImage: ubuntu-latest
steps:
- script: echo Hello, world!
displayName: 'Run a one-line script'
- script: |
echo Add other tasks to build, test, and deploy your project.
echo See https://aka.ms/yaml
displayName: 'Run a multi-line script'
```
also `output/config.yaml`:
```
pipelines:
- project_slug: valet-testing/unit/basic-pipeline-sample
source_file_path: output/pipeline.yml
- project_slug: valet-testing/unit/directed-acrylic-graph-pipeline
source_file_path: output/pipeline.yml
```
Regular commands: 
`dotnet run --project …
> Updating options on GH-Actions-Importer with new ADO options

- src/ActionsImporter.UnitTests/Services/DockerServiceTests.cs
- src/ActionsImporter/Interfaces/IRuntimeService.cs
- src/ActionsImporter/Program.cs
- src/ActionsImporter/Services/DockerService.cs
- src/ActionsImporter/Services/RuntimeService.cs
* Forwards two new environment variables to the docker image when on Linux operating systems
* The actions importer CLI recognizes these variables and will change ownership of the given output directory to the user's id and group id
* Unit tests
* Additional validation performed internally against importer-labs
Fixes #23
> Forward USER_ID and GROUP_ID to actions-importer on Linux

- src/ActionsImporter.UnitTests/AppTests.cs
- src/ActionsImporter.UnitTests/Services/DockerServiceTests.cs
- src/ActionsImporter/App.cs
- src/ActionsImporter/Commands/Common.cs
- src/ActionsImporter/Commands/ContainerCommand.cs
- src/ActionsImporter/Commands/Update.cs
- src/ActionsImporter/Commands/Version.cs
- src/ActionsImporter/Interfaces/IDockerService.cs
- src/ActionsImporter/Program.cs
- src/ActionsImporter/Services/DockerService.cs
* Adds a flag `--prerelease` for all options which will use the `:pre` tagged Docker image.
* This assists with testing preview changes, such as major version upgrades. 
* Unit tests
* I ran thru the commands to check that the `--prerelease` command is present and supported
* If reviewers could try `update --prerelease` and `version --prerelease` options as well, that'd be great! 
Closes github/valet#5280
> Implement a --prerelease global option

- src/ActionsImporter/Commands/AzureDevOps/Audit.cs
- src/ActionsImporter/Commands/AzureDevOps/BuildPipeline/DryRun.cs
- src/ActionsImporter/Commands/AzureDevOps/BuildPipeline/Migrate.cs
- src/ActionsImporter/Commands/AzureDevOps/Common.cs
- src/ActionsImporter/Commands/Circle/Audit.cs
- src/ActionsImporter/Commands/Circle/Common.cs
- src/ActionsImporter/Commands/Circle/DryRun.cs
- src/ActionsImporter/Commands/Circle/Migrate.cs
- src/ActionsImporter/Commands/GitLab/Audit.cs
- src/ActionsImporter/Commands/GitLab/Common.cs
- src/ActionsImporter/Commands/GitLab/DryRun.cs
- src/ActionsImporter/Commands/GitLab/Migrate.cs
- src/ActionsImporter/Commands/Jenkins/Audit.cs
- src/ActionsImporter/Commands/Jenkins/Common.cs
- src/ActionsImporter/Commands/Jenkins/DryRun.cs
- src/ActionsImporter/Commands/Jenkins/Migrate.cs
- src/ActionsImporter/Commands/Travis/Audit.cs
- src/ActionsImporter/Commands/Travis/Common.cs
- src/ActionsImporter/Commands/Travis/DryRun.cs
- src/ActionsImporter/Commands/Travis/Migrate.cs
Adding `--config-file-path` option to all providers. 
Make sure you have the latest version of the Valet container: 
`gh actions-importer update`
Build c# project:
`dotnet build src/ActionsImporter/ActionsImporter.csproj `
.
.
.
.
.
<details>
<summary>Azure DevOps commands</summary>
`output/ado/pipeline.yml`
```
trigger:
- main
pool:
vmImage: ubuntu-latest
steps:
- script: echo Hello, world!
displayName: 'Run a one-line script'
- script: |
echo Add other tasks to build, test, and deploy your project.
echo See https://aka.ms/yaml
displayName: 'Run a multi-line script'
```
also `output/ado/config.yaml`:
```
source_files:
- repository_slug: valet-testing/build-playground
path: output/ado/pipeline.yml
- repository_slug: valet-testing/unit/directed-acrylic-graph-pipeline
path: …
```
> Added `--config-file-path` option to all migrate and dry run commands 

- .github/workflows/ci.yml
There seems to be an incompatibility between .NET versions when running `dotnet format`. Running the command inside the `src` directory works around the issue by forcing the CLI to use the same version defined in the `src/global.json` file.
By running the CI workflow
> Fix CI lint error

- src/ActionsImporter/Program.cs
Adds the feedback board link only to the root help menu.
This also re-enables all of the descriptions for each command at the top
of the command or sub-command help menu. There was a commit a ways back that [removed descriptions](https://github.com/github/gh-actions-importer/commit/12cd38deb2ecdc9d488675b427d8d6bf4531e729) _along with usage_ from all the commands. The removal of the `usage` command was correct, since that spits out the dotnet cli command (not the `gh` cli extension one), but the descriptions shouldn't have been removed.
The usage command is the second item in the enumerable custom help builder, so I updated that to just remove the second element (the usage one) and bring back the description.
Run `dotnet run --project src/ActionsImporter/ActionsImporter.csproj -- --help` …
> Add feedback link to main help menu

- .github/workflows/ci.yml
Adds required permissions for publishing unit test results.
Docs: https://github.com/EnricoMi/publish-unit-test-result-action#permissions
- Green CI checks.
- There is a comment with the unit test results.
> CI: add required permissions for publishing unit test results

- docs/circle_ci/Orbs/Docker/Check.md
- docs/circle_ci/Orbs/Docker/InstallDockerCredentialHelper.md
- docs/circle_ci/Orbs/Docker/InstallDockerize.md
- docs/circle_ci/Orbs/Docker/Publish.md
- docs/circle_ci/Orbs/Node/InstallPackages.md
- docs/circle_ci/Orbs/Node/Run.md
- docs/circle_ci/Orbs/Node/Test.md
- docs/circle_ci/Orbs/Python/InstallPackages.md
- docs/circle_ci/Orbs/Python/Test.md
- docs/circle_ci/Orbs/Slack/Notify.md
- docs/circle_ci/Orbs/Slack/OnHold.md
- docs/jenkins/Post.md
- docs/travis_ci/Cache/Yarn.md
All code changes have been deployed already, and this change updates the public facing transformer docs to not reference the `set-output` workflow command.
:eyes:
> Update docs to deprecate set-output usage

- docs/gitlab/Trigger.md
- docs/gitlab/index.md
This adds transformer docs for the GitLab `trigger` tag
:eyes:
> Add docs for multi-project pipelines

- src/ActionsImporter/Commands/Common.cs
- src/ActionsImporter/Models/ParserExtensions.cs
- src/ActionsImporter/Program.cs
This adds an `--experimental` flag to CLI commands to bypass command line validation in the c# frontend. This will enable users to send unpublished CLI commands/arguments to the docker image to test out experimental features.
```bash
$ dotnet run --project src/ActionsImporter/ActionsImporter.csproj -- command --doesnt-exist --experimental
```
> Add experimental flag to bypass arg validation

- src/ActionsImporter/Commands/Common.cs
- src/ActionsImporter/Commands/ListFeatures.cs
- src/ActionsImporter/Program.cs
* Adds public facing commands for customers to interact with customer facing feature flags.
* _Note_ This interface is a little clunky atm, but not many customers use `--features` atm. There is follow-up work to investigate storing this in a credentials file and/or as env variables.
* Specs
* Running some commands locally:
* **Note** You will need to pull the latest docker image before running these commands 
* `dotnet run --project src/ActionsImporter/ActionsImporter.csproj -- list-features`
* `dotnet run --project src/ActionsImporter/ActionsImporter.csproj --  dry-run circle-ci -o tmp/circle --source-file-path tmp/config.yml --circle-ci-project rails-demo --disable-features=workflow-concurrency-option-allowed actions/cache`
* This should result in an output file that comments out the …
> Add list-features, --enable-features, & --disable-features

- src/ActionsImporter.UnitTests/Models/FeatureTests.cs
- src/ActionsImporter.UnitTests/Services/ConfigurationServiceTests.cs
- src/ActionsImporter.UnitTests/Services/DockerServiceTests.cs
- src/ActionsImporter/App.cs
- src/ActionsImporter/Commands/Configure.cs
- src/ActionsImporter/Commands/ListFeatures.cs
- src/ActionsImporter/Handlers/ConfigureHandler.cs
- src/ActionsImporter/Interfaces/IConfigurationService.cs
- src/ActionsImporter/Interfaces/IDockerService.cs
- src/ActionsImporter/Models/Feature.cs
- src/ActionsImporter/Program.cs
- src/ActionsImporter/Services/ConfigurationService.cs
- src/ActionsImporter/Services/DockerService.cs
This uses the changes from github/valet#5879 to fetch available flags
via the list-features --json flag. It parses out the possible env vars
and walks the customer through setting any feature flags they desire.
This is done by adding a new configure flag: `gh actions-importer configure --optional-features` which walks the user through enabling or disabling available feature flags.
If there are any issues getting the available feature flags JSON, we initialize an empty list of flags and make sure the customer is up to date.
https://user-images.githubusercontent.com/13201458/229934268-87102184-b16b-4482-b8aa-bb277150f840.mov
* Specs
* A few commands:
* If you run configure _before_ using the new docker container introduced in github/valet#5879 (`dotnet run --project …
> Update configure command to support configuring feature flags

- .github/workflows/ci.yml
- src/ActionsImporter/ActionsImporter.csproj
This builds a native darwin-arm64 binary so that Rosetta is not needed to be installed on an Apple silicon machine to run the CLI extension.
We'll publish an ad-hoc release and verify it functions on both Apple and Intel chip machines
Related to #104
> Build Apple arm64 binary

- src/ActionsImporter.UnitTests/Services/DockerServiceTests.cs
- src/ActionsImporter/Services/DockerService.cs
Currently, the Docker container uses a "bridged" network stack, which can have strange and unexpected behaviors when those network settings differ from the host's network settings.
For example, supplying an address to an private/internally-resolvable host will cause gh actions-importer to fail to resolve because it does not have those DNS settings.
This PR changes the way that the Docker container is executed by passing the `--network=host` flag, which will run this container using the host's network stack. In theory, this shouldn't break anything.
Has not been tested yet.
> Use host's network stack, not container's.

- src/ActionsImporter.UnitTests/Models/VariableTests.cs
- src/ActionsImporter/Constants.cs
- src/ActionsImporter/Models/Provider.cs
- src/ActionsImporter/Models/Variable.cs
- src/ActionsImporter/Services/ConfigurationService.cs
🚧 DO NOT MERGE UNTIL BAMBOO BETA RELEASE 🚧 
----
* Adds Bamboo support to the `configure` command.
* I also updated the configure list of providers to use the Enum so that it's dynamic
* Specs
* Run `dotnet run --project src/ActionsImporter/ActionsImporter.csproj -- configure` and run through the Bamboo option
Closes github/valet#5755
> Add Bamboo support to configure command

- src/ActionsImporter/Commands/Bamboo/Audit.cs
- src/ActionsImporter/Commands/Bamboo/Common.cs
Fixes that came out of manual testing by the team. 
To be merged after https://github.com/github/valet/pull/6208. Those changes fix a bug we found when running
```
audit bamboo -o tmp/ --confi-file-path some.yml
```
Manually
For the commands that take in `--source-file-path` I took a copy of the YAML of the `IN-COM` build and saved it locally. For the `migrate` commands I created a private repo and tested against that. 
The following commands have all succeeded. I'll update this block as a I go.
```sh
export PROJ=src/ActionsImporter/ActionsImporter.csproj
dotnet run --project $PROJ -- audit bamboo -o tmp/
dotnet run --project $PROJ -- audit bamboo -o tmp/ --project IN
dotnet run --project $PROJ -- audit bamboo -o tmp/ -p IN
dotnet run --project $PROJ -- dry-run bamboo deployment -o tmp/ …
```
> Fix: command option types

- src/ActionsImporter/Commands/Bamboo/Forecast.cs
- src/ActionsImporter/Commands/Forecast.cs
Exposes the `forecast` command for Bamboo
Try it out!
```
dotnet run --project src/ActionsImporter/ActionsImporter.csproj -- forecast bamboo -o output/audit
dotnet run --project src/ActionsImporter/ActionsImporter.csproj -- forecast bamboo -o output/audit --start-date 01/01/2023
```
> Note make sure to pull the latest container to ensure you have forecast support with `gh actions-importer update`
👀 
Closes github/valet/issues/6233
> Expose `forecast` command for Bamboo

- src/ActionsImporter/Program.cs
* Add an env var `TEST_COMMAND_ONLY`, which only runs the CLI parser
* Exits 1 or 0 depending on parser result
* Prints errors to console
* For use by https://github.com/github/valet/pull/6289 
* This allows us to run commands _only_ to see if the two CLIs are "in sync" and help us find which options from the Ruby side aren't supported here
Open to better ENV var name suggestions! Also if there's somewhere else I can put this other than `Program.cs` I'd love to know, as that file is getting somewhat long and complex.
```shell
TEST_COMMAND_ONLY=true dotnet run --project src/ActionsImporter/ActionsImporter.csproj -- dry-run bamboo build -o tmp -p proj
TEST_COMMAND_ONLY=true dotnet run --project src/ActionsImporter/ActionsImporter.csproj -- dry-run bamboo build
dotnet run --project …
```
> Add a mode that validates CLI commands/options only

- src/ActionsImporter.UnitTests/Services/DockerServiceTests.cs
- src/ActionsImporter/App.cs
- src/ActionsImporter/Commands/Common.cs
- src/ActionsImporter/Commands/ContainerCommand.cs
- src/ActionsImporter/Interfaces/IDockerService.cs
- src/ActionsImporter/Program.cs
- src/ActionsImporter/Services/DockerService.cs
Adds a new CLI flag `--no-host-network` to prevent the use of the host network while running the docker commands.  If the flag is not present then the docker run command is generate as it was before with the `--network=host`.  When the new flag is present the `--network=host` will not be added.  
Relates to #172 
specs and 👀 
Closes github/valet/issues/6619
> Add option to disable the use of host network

- src/ActionsImporter/Commands/GitHub/Forecast.cs
* Add the `--include-from` option to support splitting GitHub forecasts across multiple machines/CLI invocations.
* Run `dotnet run --project src/ActionsImporter/ActionsImporter.csproj -- forecast github --help` and see that the new --include-from option is included and matches the one in github/valet#6672
Closes github/valet#6618
> Add --include-from option to GitHub forecast

- src/ActionsImporter/Commands/Bitbucket/Forecast.cs
- src/ActionsImporter/Commands/Forecast.cs
Adds `forecast` command to Bitbucket
Try it out 🚗 
```shell
dotnet run --project src/ActionsImporter/ActionsImporter.csproj -- forecast bitbucket --workspace actions-importer -o output/forecast 
```
With `--project-key`
```shell
dotnet run --project src/ActionsImporter/ActionsImporter.csproj -- forecast bitbucket --workspace actions-importer -o output/forecast --project-key SW
```
👀 
Closes github/valet#7012
> Bitbucket:  Add support for `forecast` command

- docs/circle_ci/Orbs/Cypress/Setup.md
Remove `verify-command` example from the `CircleCI` docs.
Visual. It's just a docs change.
Closes https://github.com/github/valet/issues/7264
> Remove verify-command sample

- .github/workflows/ci.yml
- CODE_OF_CONDUCT.md
- Pinned `dotnet-format` to `v5.1.225507` to ensure compatibility with `.NET 6.0`.
- Pinned `ThirdLicense` to `v1.2.0`, the last version compatible with `.NET 6.0`.
- Bumped the version of `actions/upload-artifact` from `v3` to `v4`
- Updated artifact upload step to use a **dynamically generated name** via `${{ github.run_id }}` to avoid naming collisions and potential infra-related cache issues.
- Confirmed workflows run on **GitHub-hosted runners**, not Azure Pipelines.
- Added preparation logic to organize `dotnet publish` output into a unified staging directory before uploading artifacts.
- ✅ Lint passes using the pinned version of `dotnet-format`.
- ✅ Tests and license validation succeed using compatible tool versions.
The workflow previously failed due to:
- CI tools installing …
> Fix CI Failures by Pinning .NET Tool Versions
